### ISSUE TITLE
Nox does not update NixOS package system config?

### ISSUE THREAD

**Issue by Trevoke** [madjar/nox#23]
For some reason I expected Nox to update the package config, but it doesn't. Does it make sense for Nox to do that, and can I request that as a new feature?

**Comment by madjar** [comment]
Nox only handles the user-specific packages, like nix-env does (it is little more than a nix-env wrapper, actually).

You can of course request that as a new feature, but it's a big one, because that requires parsing and rewriting the configuration.nix, which is no small task. It's is unlikely I'll implement it anytime soon.

**Comment by Trevoke** [comment]
Oh, then I mistook nox's purpose (and Nix's behavior). Thanks for explaining it!
